apiVersion: v1
kind: Service
metadata:
  name: trading-app
  labels:
    app: trading-app
spec:
  ports:
    - port: 80 #port exposed
      targetPort: 8080 #port forwarded
  selector:
    app: trading-app
    tier: app-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-app
  labels:
    app: trading-app
spec:
  selector:
    matchLabels:
      app: trading-app
      tier: app-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trading-app
        tier: app-server
    spec:
      containers:
      - image: phuongly/trading-app:latest
        name: trading-app
        env:
        - name: PSQL_URL
          value: jdbc:postgresql://trading-psql:5432/jrvstrading
        - name: PSQL_USER
          value: postgres
        - name: PSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql-pass
              key: password
        - name: IEX_PUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: iex-token
              key: value
        ports:
        - containerPort: 8080
          name: trading-app
